env: "local"
grpc:
  port: 44044
  timeout: 3s
clients:
  receiver:
    address: ":44044"
    retries_count: 5
    timeout: 3s
    insecure: true
coefficient: 1.2
postgres:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "postgres"
  db_name: "postgres"
  ssl_mode: "disable"